name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.3', '8.2', '8.1', '8.0' ]
        hyperf: [ '~3.0.0', '~3.1.0' ]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - hyperf: '~3.1.0'
            php: '8.0'
          - hyperf: '~3.0.0'
            php: '8.3'
      max-parallel: 12
      fail-fast: false

    name: PHP${{ matrix.php }} - Hyperf${{ matrix.hyperf }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: swoole-5.1.1
          ini-values: swoole.use_shortname=Off
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require "hyperf/di:${{ matrix.hyperf }}"
          composer require "hyperf/http-server:${{ matrix.hyperf }}"
          composer require "hyperf/config:${{ matrix.hyperf }}" --dev
          composer require "hyperf/testing:${{ matrix.hyperf }}" --dev
          composer require "hyperf/validation:${{ matrix.hyperf }}" --dev
          composer update --${{ matrix.dependency-version }} --no-progress

      - name: Run Test Cases
        run: composer test
